### ISSUE TITLE
Addon does not start under Operating System 14.0

### ISSUE THREAD

**Issue by watersnake154** [Buktahula/hassio-addons#11]
The addon no longer starts since the operating system was updated to 14.0.

Log:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[19:48:51] INFO: Initialize the essmqtt configuration...
Traceback (most recent call last):
  File "/usr/local/bin/essmqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 120, in main
    asyncio.run(_main(arguments))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 151, in _main
    ip, name = await loop.run_in_executor(None, autodetect_ess)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyess/ess.py", line 218, in autodetect_ess
    name = find_all_esses()[0]
  File "/usr/local/lib/python3.8/site-packages/pyess/ess.py", line 266, in find_all_esses
    raise ESSException("could not find any ESS devices via mdns")
pyess.ess.ESSException: could not find any ESS devices via mdns
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by watersnake154** [comment]
Problem was caused by the Upadte, but by a faulty software of the Fritz.Box.

Problem solved.
