### ISSUE TITLE
sensors not available 

### ISSUE THREAD

**Issue by Leedrag** [Buktahula/hassio-addons#4]
Since I have updated my HA OS to 3023.09.3 and the addon to 0.0.6 simultaneously any sensors are available anymore.

The log says the following. What’s the problem?

-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[11:33:53] INFO: Initialize the essmqtt configuration...
INFO:pyess.aio_ess:fetching auth key
INFO:pyess.essmqtt:starting send loop
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-17' coro=<_main.<locals>.handle_control() done, defined at /usr/local/lib/python3.8/site-packages/pyess/essmqtt.py:180> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 182, in handle_control
    async for msg in messages:
  File "/usr/local/lib/python3.8/site-packages/aiomqtt/client.py", line 857, in _generator
    raise MqttError(msg)
aiomqtt.error.MqttError: Disconnected during message iteration
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-18' coro=<_main.<locals>.handle_control() done, defined at /usr/local/lib/python3.8/site-packages/pyess/essmqtt.py:180> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 182, in handle_control
    async for msg in messages:
  File "/usr/local/lib/python3.8/site-packages/aiomqtt/client.py", line 857, in _generator
    raise MqttError(msg)
aiomqtt.error.MqttError: Disconnected during message iteration
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-19' coro=<_main.<locals>.handle_control() done, defined at /usr/local/lib/python3.8/site-packages/pyess/essmqtt.py:180> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 182, in handle_control
    async for msg in messages:
  File "/usr/local/lib/python3.8/site-packages/aiomqtt/client.py", line 857, in _generator
    raise MqttError(msg)
aiomqtt.error.MqttError: Disconnected during message iteration
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-23' coro=<_main.<locals>.handle_control() done, defined at /usr/local/lib/python3.8/site-packages/pyess/essmqtt.py:180> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 182, in handle_control
    async for msg in messages:
  File "/usr/local/lib/python3.8/site-packages/aiomqtt/client.py", line 857, in _generator
    raise MqttError(msg)
aiomqtt.error.MqttError: Disconnected during message iteration
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-24' coro=<_main.<locals>.handle_control() done, defined at /usr/local/lib/python3.8/site-packages/pyess/essmqtt.py:180> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 182, in handle_control
    async for msg in messages:
  File "/usr/local/lib/python3.8/site-packages/aiomqtt/client.py", line 857, in _generator
    raise MqttError(msg)
aiomqtt.error.MqttError: Disconnected during message iteration
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-25' coro=<_main.<locals>.handle_control() done, defined at /usr/local/lib/python3.8/site-packages/pyess/essmqtt.py:180> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 182, in handle_control
    async for msg in messages:
  File "/usr/local/lib/python3.8/site-packages/aiomqtt/client.py", line 857, in _generator
    raise MqttError(msg)
aiomqtt.error.MqttError: Disconnected during message iteration
WARNING:pyess.essmqtt:Expected exception while talking go ESS or MQTT server, restarting in 60 seconds.Usually this means the server is slow to respond or unreachable.
INFO:pyess.aio_ess:fetching auth key
INFO:pyess.essmqtt:starting send loop

**Comment by Buktahula** [comment]
Is your MQTT Server Up and running without errors?

**Comment by Leedrag** [comment]
just says this:
2023-10-04 11:45:53: New connection from ***:51523 on port 1883.
2023-10-04 11:45:53: New client connected from ***:51523 as auto-7B8E6AF0-0922-03D9-F0A7-F9021A006B00 (p2, c1, k60, u'*****mqtt').
2023-10-04 11:47:40: New connection from 172.30.32.2:39986 on port 1883.
2023-10-04 11:47:40: Client <unknown> closed its connection.

**Comment by Buktahula** [comment]
I reported the problem at https://github.com/gluap/pyess and am waiting for feedback

**Comment by Buktahula** [comment]
the problem is still there

**Comment by Buktahula** [comment]
Nö response
